config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    # タイトルが存在し、最大20文字であることを確認するバリデーション
  validates :title, presence: true, length: { maximum: 20 }

   # 開始日と終了日の存在を確認
   validates :start_date, :end_date, presence: true

   # 終了日が開始日以降であることを確認するカスタムバリデーション
   validate :end_date_is_after_start_date
 
   private
 
   def end_date_is_after_start_date
     return if end_date.blank? || start_date.blank?
 
     if end_date < start_date
       errors.add(:end_date, 'は開始日以降の日付を選択してください。')
     end
   end

   validates :schedule_memo, length: { maximum: 500 }
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
  @schedule = Schedule.new  # ここでの変更点: 'schedules' から '@schedule' へ、'schedule' から 'Schedule' へ
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :schedule_memo))
    if @schedule.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to :schedules
    else
      render "new"
  end
end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :schedule_memo))
      flash[:notice] = "スケジュールIDが「#{@schedule.id}」の情報を更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
      flash[:notice] = "スケジュールを削除しました"
      redirect_to :schedules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <footer>
  <p>本日の日付: <%= Date.today.strftime('%Y年%m月%d日') %></p>
</footer>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<h3>スケジュール編集</h3>

<%= form_with model: @schedule do |f| %>
    <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date, "開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date, "終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>

    <tr>
      <th><%= f.label :all_day, '終日の場合はチェックを入れます' %></th>
      <td><%= f.check_box :all_day %></td>
    </tr>

    <tr>
      <th><%= f.label :schedule_memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :schedule_memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "更新する" %></li>
      <li><%= link_to "予定一覧に戻る", :schedules %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/index.html.erb
<header>
  <h1>スケジュール管理アプリ</h1>
</header>

<h2>予定一覧</h2>

<p><%= link_to '➕新規追加', new_schedule_path, class: 'btn btn-primary' %></p>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.start_date.strftime("%Y/%m/%d") if schedule.start_date %></td>
        <td><%= schedule.end_date.strftime("%Y/%m/%d") if schedule.end_date %></td>
        <td><%= schedule.all_day ? '○' : '' %></td>
        <td><%= schedule.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= link_to '詳細', schedule_path(schedule) %></td>
        <td><%= link_to '編集', edit_schedule_path(schedule) %></td>
        <td><%= link_to '削除', schedule_path(schedule), method: :delete, data: { confirm: '予定を削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>予定合計 <%= @schedules.count %> 件</p>

app/views/schedules/new.html.erb
<h3>予定の新規追加</h3>

<%= form_with model: @schedule, local: true do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <% if @schedule.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

    <ul>
    <% @schedule.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


    <tr>
      <th><%= f.label :start_date, "開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date, "終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>

    <tr>
      <th><%= f.label :all_day, '終日の場合はチェックを入れます' %></th>
      <td><%= f.check_box :all_day %></td>
    </tr>

    <tr>
      <th><%= f.label :schedule_memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :schedule_memo %></td>
    </tr>

    <% if @schedule.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

    <ul>
    <% @schedule.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  </table>

  <div>
    <ul>
      <li><%= f.submit "保存する" %></li>
      <li><%= link_to "キャンセル", schedules_path %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/show.html.erb
<h3>予定詳細</h3>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.start_date %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @schedule.end_date %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><%= @schedule.all_day ? '○' : '' %></td>
  </tr>  
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @schedule.schedule_memo %>
    </td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "予定一覧に戻る", :schedules %></li>
  </ul>
</div>